# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "deploy" branch
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
         key: ${{ secrets.SSH_KEY }}
         known_hosts: ${{ secrets.HOSTNAME }}
         name: id_rsa # optional
         if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      # Runs a single command using the runners shell
      - name: access server
        run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOSTNAME }} "mkdir /tmp/testu"
#      - name: Run a one-line script
#        run: mkdir /tmp/testing

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #   echo Add other actions to build,
     #    echo test, and deploy your project.
